#!/usr/bin/env bash

set -e

WORK_DIR=/usr/src

function handle_error() {
  local status=$?
  if [[ $status > 0 ]]; then
    echo "🔥 There was a problem building the binary. Operation aborted."
    exit 1
  fi
}
trap handle_error EXIT SIGINT

function add_xenial_repositories() {
  cat <<-EOT >> /etc/apt/sources.list
  deb [trusted=yes] http://archive.ubuntu.com/ubuntu/ xenial main universe
  deb [trusted=yes] http://security.ubuntu.com/ubuntu xenial-security main
EOT
}

# add source packages repository to sources.list
function add_source_repositories() {
  gpg --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
  gpg --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
  echo "deb-src [trusted=yes] http://archive.ubuntu.com/ubuntu/ xenial main universe" >> /etc/apt/sources.list
  add_xenial_repositories
}

add_source_repositories

echo "⚙️ Getting libraries and dependencies..."
apt-get update -y --allow-unauthenticated
apt-get install -y build-essential autoconf libtool git-core
echo "⚙️ Getting additional dependencies for the selected stack..."
apt-get install -y libomp5 libomp-dev libjasper-dev
apt-get build-dep -y imagemagick libmagickcore-dev

# install the libde265 library
echo "⚙️ Installing and configuring libde265..."
git clone https://github.com/strukturag/libde265.git $WORK_DIR/libde265
cd $WORK_DIR/libde265
./autogen.sh && ./configure && make && make install

# install the libheif library
echo "⚙️ Installing and configuring libheif..."
git clone https://github.com/strukturag/libheif.git $WORK_DIR/libheif
cd $WORK_DIR/libheif
mkdir build
cd build
cmake --preset=release ..
make && make install

# get, configure and install imagemagick
echo "⚙️ Installing imagemagick..."
wget https://imagemagick.org/archive/ImageMagick-6.9.13-16.tar.gz -P $WORK_DIR
cd $WORK_DIR
mkdir imagemagick
tar xvfz ImageMagick-6.9.13-16.tar.gz -C $WORK_DIR/imagemagick --strip-components=1
cd $WORK_DIR/imagemagick
./configure --with-heic=yes --prefix=$WORK_DIR/imagemagick --without-gvc
make && make install

# copy the dependencies into imagemagick lib directory
cp /usr/local/lib/libde265.so.0 $WORK_DIR/imagemagick/lib
cp /usr/local/lib/libheif.so.1 $WORK_DIR/imagemagick/lib
cp /usr/lib/x86_64-linux-gnu/libomp.so.5 $WORK_DIR/imagemagick/lib
cp /usr/lib/x86_64-linux-gnu/libiomp5.so $WORK_DIR/imagemagick/lib

# clean up the build and get ready for packaging
echo "🧹 Cleaning up..."
strip lib/*.a lib/lib*.so*

# compress the binary
echo "🗄️ Compressing build..."
rm -rf build
mkdir build
tar czf $WORK_DIR/imagemagick/build/imagemagick.tar.gz bin include lib

# copy the compressed file/tarball from the docker container into the repo
cp $WORK_DIR/imagemagick/build/imagemagick.tar.gz /buildpack/build/$1

echo "✅ All done!"
